<template>
	<h2><a href="https://vuetifyjs.com/en/components/buttons">buttons</a></h2>
	<VuetifyExamplesSnippetsButtons1 />
	<hr />
	<VuetifyExamplesSnippetsButtons2 />
	<hr />
	<VuetifyExamplesSnippetsButtons3 />
	<hr />
	<VuetifyExamplesSnippetsButtons4 />
	<hr />
	<VuetifyExamplesSnippetsButtons5 />
	<hr />
	<VuetifyExamplesSnippetsButtons6 />
	<hr />
	<VuetifyExamplesSnippetsButtons7 />
	<hr />
	<VuetifyExamplesSnippetsButtons8 />
	<hr />
	<VuetifyExamplesSnippetsButtons9 />
	<hr />
	<VuetifyExamplesSnippetsButtons10 />
	<hr />
	<VuetifyExamplesSnippetsButtons11 />
	<hr />
	<VuetifyExamplesSnippetsButtons12 />
	<hr />
	<VuetifyExamplesSnippetsButtons13 />
	<hr />
	<VuetifyExamplesSnippetsButtons14 />
	<hr />
	<VuetifyExamplesSnippetsButtons15 />
	<hr />
	<VuetifyExamplesSnippetsButtons16 />
	<hr />
	<VuetifyExamplesSnippetsButtons17 />
	<hr />
	<VuetifyExamplesSnippetsButtons18 />
	<hr />
	<VuetifyExamplesSnippetsButtons19 />
	<hr />
	<VuetifyExamplesSnippetsButtons20 />
	<hr />
	<VuetifyExamplesSnippetsButtons21 />
	<hr />
	<VuetifyExamplesSnippetsButtons22 />
	<hr />
</template>
