<template>
	<h2><a href="https://vuetifyjs.com/en/styles/flex">flex</a></h2>
	<VuetifyExamplesSnippetsFlex1 />
	<hr />
	<VuetifyExamplesSnippetsFlex2 />
	<hr />
	<VuetifyExamplesSnippetsFlex3 />
	<hr />
	<VuetifyExamplesSnippetsFlex4 />
	<hr />
	<VuetifyExamplesSnippetsFlex5 />
	<hr />
	<VuetifyExamplesSnippetsFlex6 />
	<hr />
	<VuetifyExamplesSnippetsFlex7 />
	<hr />
	<VuetifyExamplesSnippetsFlex8 />
	<hr />
	<VuetifyExamplesSnippetsFlex9 />
	<hr />
	<VuetifyExamplesSnippetsFlex10 />
	<hr />
	<VuetifyExamplesSnippetsFlex11 />
	<hr />
	<VuetifyExamplesSnippetsFlex12 />
	<hr />
	<VuetifyExamplesSnippetsFlex13 />
	<hr />
	<VuetifyExamplesSnippetsFlex14 />
	<hr />
	<VuetifyExamplesSnippetsFlex15 />
	<hr />
	<VuetifyExamplesSnippetsFlex16 />
	<hr />
	<VuetifyExamplesSnippetsFlex17 />
	<hr />
	<VuetifyExamplesSnippetsFlex18 />
	<hr />
	<VuetifyExamplesSnippetsFlex19 />
	<hr />
	<VuetifyExamplesSnippetsFlex20 />
	<hr />
</template>
